#! /bin/bash
clear
while :
do
    echo -e "\e[1;93mTest Control Pannel\e[39m\n\n"

    echo -e "1] Create Private TAG Service"
    # (Launch a program that creates x receiver and y sender)
    echo -e "2] Create TAG Service"
    echo -e "3] Spawn Receiver"
    echo -e "4] Spawn Sender"
    echo -e "5] Delete TAG Service"
    echo -e "6] Awake All"
    echo -e "7] Brute Force Test"
    echo -e "8] Automatic Send-Receive Test"
    echo -e "9] Launch Monitor (TAG Driver)"
    echo -e "10] Exit"

    read -p "Your choice: " choice

    case $choice in
        1) xterm -e unit/create_priv_tag &
        ;;
        2) read -p "Insert Key: " key
           read -p "Permission (user=0, any=1): " perm
           unit/create_tag $perm $key
           sleep 1
        ;;
        3) read -p "Insert TAG Key: " key
           read -p "Insert Level: " lvl
           xterm -e unit/spawn_receiver $key $lvl &
        ;;
        4) read -p "Insert TAG Key: " key
           read -p "Insert Level: " lvl
           xterm -e unit/spawn_sender $key $lvl &
        ;;
        5) read -p "Insert TAG Key: " key
           xterm -e unit/delete_tag $key &
        ;;
        6) read -p "Insert TAG Key: " key
           xterm -e unit/awake_all $key &
        ;;
        7) xterm -e "system/brute_force" &
        ;;
        8) read -p "Num Receiving threads: " num
           xterm -e "system/tag_receive" $num &
        ;;
        9) xterm -e "cd ./system && ./monitoring" &
	    ;;
        10) exit
	    ;;
        *) echo "What?"
        ;;
    esac

    clear
done
