all:
	gcc create_tag.c -o create_tag
	gcc spawn_receiver.c -o spawn_receiver
	gcc spawn_sender.c -o spawn_sender
	gcc create_priv_tag.c -o create_priv_tag
	gcc delete_tag.c -o delete_tag
	gcc awake_all.c -o awake_all
clean:
	rm create_tag spawn_receiver spawn_sender create_priv_tag awake_all delete_tag
