all:
	gcc tag_get.c -o tag_get
	gcc tag_receive.c -o tag_receive
	gcc brute_force.c -o brute_force
	gcc send_receive.c -o send_receive
	gcc awake_all.c -o awake_all
clean:
	rm tag_get awake_all send_receive brute_force tag_receive
